version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    command: sh -c "yarn start"
    ports:
      - "8080:8080"
    stdin_open: true